apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
    - name: container-application-loja
      image: rafanercessian/aplicacao-loja:v1
      ports:
        - containerPort: 80
