apiVersion: v1
kind: Deployment
  metadata:
    name: application-deployment
  spec:
    template:
      metadata:
        labels:
          name: application-pod
      spec:
        containers:
          - name: container-application-loja
            image: rafanercessian/aplicacao-loja:v1
            ports:
              - containerPort: 80
